### PR TITLE
[16.0][FIX] pos_order_to_sale_order

### PR DESCRIPTION
**Pull request by geomer198**
Code refactoring and fix comments in this [PR](https://github.com/OCA/pos/pull/1080).

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @geomer198.
Test are green here : https://github.com/OCA/pos/pull/1080
but red in the current PR. could you take a look ? thanks !

**Comment by geomer198** [comment]
> Hi @geomer198. Test are green here : [OCA#1080](https://github.com/OCA/pos/pull/1080) but red in the current PR. could you take a look ? thanks !

I don't have idea about reason errors in the tests. Errors throw in `stock_available` module. This module doesn't depend on current fixes.

**Comment by geomer198** [comment]
@legalsylvain Could you check?

**Comment by legalsylvain** [comment]
Hi @geomer198. 
sorry, I'm totally busy for the next weeks. Maybe it's better to merge https://github.com/OCA/pos/pull/1080 (because the CI is green), and then you make your PR directly against the OCA repo ? It maybe will solve the CI trouble.

Let me know !

**Comment by geomer198** [comment]
> Hi @geomer198. sorry, I'm totally busy for the next weeks. Maybe it's better to merge [OCA#1080](https://github.com/OCA/pos/pull/1080) (because the CI is green), and then you make your PR directly against the OCA repo ? It maybe will solve the CI trouble.
> 
> Let me know !

Agree with you! Let's do this.

**Pull request closed without merging**
